# Generated by Django 5.0.7 on 2024-07-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubwayStation',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='subwaystation',
        ),
    ]
