# Generated by Django 5.0.7 on 2024-07-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_category_subwaystation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='subwaystation',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubwayStation',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
