# Generated by Django 5.0.7 on 2024-07-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
