# Generated by Django 5.0.7 on 2024-08-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/Users/mingikim/2024-hackathon-1-boiledtrain/static/images/default_profile.png', upload_to='user'),
        ),
    ]
