# Generated by Django 5.0.7 on 2024-08-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='media/user/default_profile.png', upload_to='user'),
        ),
    ]
