# Generated by Django 5.0.7 on 2024-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_course_title_diary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subway',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
