# Generated by Django 5.0.7 on 2024-07-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_course_subway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subway',
        ),
    ]
