# Generated by Django 5.0.7 on 2024-07-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_subway'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.subway'),
            preserve_default=False,
        ),
    ]
