# Generated by Django 5.0.7 on 2024-07-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subway',
        ),
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
