# Generated by Django 5.0.7 on 2024-07-30 11:33

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_course_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.image_upload_path
            ),
        ),
    ]
